import { AuctionItem } from "./types";

export const sampleItems: AuctionItem[] = [
  // ── check 済み（代表モードに表示） ──────────────────────────────
  {
    id: "1",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example1",
    brandName: "ルイ・ヴィトン",
    check: true,
    bidTarget: true,
    assignee: "吉川さん",
    marketPrice: 85000,
    bidPrice: 78000,
    wholesalePrice: 92000,
    referenceUrl1: "https://mercari.com/example1",
    referenceUrl2: "https://buyma.com/example1",
    referenceUrl3: "https://rakuten.co.jp/example1",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "状態良好、付属品完備",
    representativeCheck: true,
    judgmentResult: true,
    feedback: "相場より10%安く落札できた",
    feedbackConfirmed: false,
    createdAt: "2026-02-20T09:00:00Z",
    updatedAt: "2026-02-22T15:30:00Z",
  },
  {
    id: "3",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example3",
    brandName: "シャネル",
    check: true,
    bidTarget: false,
    assignee: "伊藤さん",
    marketPrice: 45000,
    bidPrice: 42000,
    wholesalePrice: null,
    referenceUrl1: "https://mercari.com/example3",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "偽物の可能性あり、真贋注意",
    representativeCheck: false,
    judgmentResult: false,
    feedback: "",
    feedbackConfirmed: false,
    createdAt: "2026-02-22T08:00:00Z",
    updatedAt: "2026-02-23T11:00:00Z",
  },
  {
    id: "5",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example5",
    brandName: "エルメス",
    check: true,
    bidTarget: true,
    assignee: "望月さん",
    marketPrice: 210000,
    bidPrice: 195000,
    wholesalePrice: 230000,
    referenceUrl1: "https://mercari.com/example5",
    referenceUrl2: "https://rakuten.co.jp/example5",
    referenceUrl3: "https://buyma.com/example5",
    referenceUrl4: "https://yahoo.co.jp/example5",
    referenceUrl5: "",
    notes: "限定品、箱・保証書付き",
    representativeCheck: false,
    judgmentResult: false,
    feedback: "",
    feedbackConfirmed: false,
    createdAt: "2026-02-23T09:00:00Z",
    updatedAt: "2026-02-23T14:00:00Z",
  },
  {
    id: "7",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example7",
    brandName: "グッチ",
    check: true,
    bidTarget: true,
    assignee: "折出さん",
    marketPrice: 68000,
    bidPrice: 63000,
    wholesalePrice: 75000,
    referenceUrl1: "https://mercari.com/example7",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "GGキャンバス、使用感あり",
    representativeCheck: false,
    judgmentResult: false,
    feedback: "",
    feedbackConfirmed: false,
    createdAt: "2026-02-23T10:00:00Z",
    updatedAt: "2026-02-23T16:00:00Z",
  },
  // ── check 未処理（社員モードに表示） ─────────────────────────────
  {
    id: "2",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example2",
    brandName: "ルイ・ヴィトン",
    check: false,
    bidTarget: false,
    assignee: "",
    marketPrice: null,
    bidPrice: null,
    wholesalePrice: null,
    referenceUrl1: "",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "",
    representativeCheck: false,
    judgmentResult: false,
    feedback: "",
    feedbackConfirmed: false,
    createdAt: "2026-02-21T10:00:00Z",
    updatedAt: "2026-02-21T10:00:00Z",
  },
  {
    id: "4",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example4",
    brandName: "プラダ",
    check: false,
    bidTarget: false,
    assignee: "",
    marketPrice: null,
    bidPrice: null,
    wholesalePrice: null,
    referenceUrl1: "",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "",
    representativeCheck: false,
    judgmentResult: false,
    feedback: "",
    feedbackConfirmed: false,
    createdAt: "2026-02-24T09:00:00Z",
    updatedAt: "2026-02-24T09:00:00Z",
  },
  {
    id: "6",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example6",
    brandName: "シャネル",
    check: false,
    bidTarget: false,
    assignee: "吉川さん",   // 以前に担当割り当て済み（マイタスクで確認できる）
    marketPrice: null,
    bidPrice: null,
    wholesalePrice: null,
    referenceUrl1: "",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "",
    representativeCheck: false,
    judgmentResult: false,
    feedback: "",
    feedbackConfirmed: false,
    createdAt: "2026-02-24T10:00:00Z",
    updatedAt: "2026-02-24T10:00:00Z",
  },
  {
    id: "8",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example8",
    brandName: "エルメス",
    check: false,
    bidTarget: false,
    assignee: "",
    marketPrice: null,
    bidPrice: null,
    wholesalePrice: null,
    referenceUrl1: "",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "",
    representativeCheck: false,
    judgmentResult: false,
    feedback: "",
    feedbackConfirmed: false,
    createdAt: "2026-02-24T11:00:00Z",
    updatedAt: "2026-02-24T11:00:00Z",
  },
];
