import { AuctionItem } from "./types";

// ── アパレル サンプルデータ ────────────────────────────────

export const sampleItemsApparel: AuctionItem[] = [
  // ── check 済み（代表モードに表示） ──────────────────────────────
  {
    id: "1",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example1",
    brandName: "ルイ・ヴィトン",
    check: true,
    bidTarget: true,
    assignee: "吉川さん",
    revisedMarketPrice: null,
    marketPrice: 85000,
    bidPrice: 78000,
    wholesalePrice: 92000,
    referenceUrl1: "https://mercari.com/example1",
    referenceUrl2: "https://buyma.com/example1",
    referenceUrl3: "https://rakuten.co.jp/example1",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "状態良好、付属品完備",
    representativeCheck: true,
    judgmentResult: true,
    feedback: "相場より10%安く落札できた",
    feedbackConfirmed: false,
    winningSuccess: true,
    auctionDate: "2026-02-15",
    createdAt: "2026-02-20T09:00:00Z",
    updatedAt: "2026-02-22T15:30:00Z",
  },
  {
    id: "3",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example3",
    brandName: "シャネル",
    check: true,
    bidTarget: false,
    assignee: "伊藤さん",
    revisedMarketPrice: null,
    marketPrice: 45000,
    bidPrice: 42000,
    wholesalePrice: null,
    referenceUrl1: "https://mercari.com/example3",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "偽物の可能性あり、真贋注意",
    representativeCheck: false,
    judgmentResult: false,
    feedback: "",
    feedbackConfirmed: false,
    winningSuccess: false,
    auctionDate: "2026-02-17",
    createdAt: "2026-02-22T08:00:00Z",
    updatedAt: "2026-02-23T11:00:00Z",
  },
  {
    id: "5",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example5",
    brandName: "エルメス",
    check: true,
    bidTarget: true,
    assignee: "望月さん",
    revisedMarketPrice: null,
    marketPrice: 210000,
    bidPrice: 195000,
    wholesalePrice: 230000,
    referenceUrl1: "https://mercari.com/example5",
    referenceUrl2: "https://rakuten.co.jp/example5",
    referenceUrl3: "https://buyma.com/example5",
    referenceUrl4: "https://yahoo.co.jp/example5",
    referenceUrl5: "",
    notes: "限定品、箱・保証書付き",
    representativeCheck: false,
    judgmentResult: true,
    feedback: "",
    feedbackConfirmed: false,
    winningSuccess: false,
    auctionDate: "2026-02-20",
    createdAt: "2026-02-23T09:00:00Z",
    updatedAt: "2026-02-23T14:00:00Z",
  },
  {
    id: "7",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example7",
    brandName: "グッチ",
    check: true,
    bidTarget: true,
    assignee: "折出さん",
    revisedMarketPrice: null,
    marketPrice: 68000,
    bidPrice: 63000,
    wholesalePrice: 75000,
    referenceUrl1: "https://mercari.com/example7",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "GGキャンバス、使用感あり",
    representativeCheck: false,
    judgmentResult: false,
    feedback: "",
    feedbackConfirmed: false,
    winningSuccess: true,
    auctionDate: "2026-02-22",
    createdAt: "2026-02-23T10:00:00Z",
    updatedAt: "2026-02-23T16:00:00Z",
  },
  // ── check 未処理（社員モードに表示） ─────────────────────────────
  {
    id: "2",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example2",
    brandName: "ルイ・ヴィトン",
    check: false,
    bidTarget: false,
    assignee: "",
    revisedMarketPrice: null,
    marketPrice: null,
    bidPrice: null,
    wholesalePrice: null,
    referenceUrl1: "",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "",
    representativeCheck: false,
    judgmentResult: false,
    feedback: "",
    feedbackConfirmed: false,
    winningSuccess: false,
    auctionDate: "2026-02-14",
    createdAt: "2026-02-21T10:00:00Z",
    updatedAt: "2026-02-21T10:00:00Z",
  },
  {
    id: "4",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example4",
    brandName: "プラダ",
    check: false,
    bidTarget: false,
    assignee: "",
    revisedMarketPrice: null,
    marketPrice: null,
    bidPrice: null,
    wholesalePrice: null,
    referenceUrl1: "",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "",
    representativeCheck: false,
    judgmentResult: false,
    feedback: "",
    feedbackConfirmed: false,
    winningSuccess: false,
    auctionDate: "2026-02-14",
    createdAt: "2026-02-24T09:00:00Z",
    updatedAt: "2026-02-24T09:00:00Z",
  },
  {
    id: "6",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example6",
    brandName: "シャネル",
    check: false,
    bidTarget: false,
    assignee: "吉川さん",
    revisedMarketPrice: null,
    marketPrice: null,
    bidPrice: null,
    wholesalePrice: null,
    referenceUrl1: "",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "",
    representativeCheck: false,
    judgmentResult: false,
    feedback: "",
    feedbackConfirmed: false,
    winningSuccess: false,
    auctionDate: "2026-02-14",
    createdAt: "2026-02-24T10:00:00Z",
    updatedAt: "2026-02-24T10:00:00Z",
  },
  {
    id: "8",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/example8",
    brandName: "エルメス",
    check: false,
    bidTarget: false,
    assignee: "",
    revisedMarketPrice: null,
    marketPrice: null,
    bidPrice: null,
    wholesalePrice: null,
    referenceUrl1: "",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "",
    representativeCheck: false,
    judgmentResult: false,
    feedback: "",
    feedbackConfirmed: false,
    winningSuccess: false,
    auctionDate: "2026-02-14",
    createdAt: "2026-02-24T11:00:00Z",
    updatedAt: "2026-02-24T11:00:00Z",
  },
];

// ── バッグ サンプルデータ ──────────────────────────────────

export const sampleItemsBags: AuctionItem[] = [
  {
    id: "b1",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/bag1",
    brandName: "ルイ・ヴィトン",
    check: true,
    bidTarget: true,
    assignee: "吉川さん",
    revisedMarketPrice: 115000,
    marketPrice: 120000,
    bidPrice: 110000,
    wholesalePrice: 135000,
    referenceUrl1: "https://mercari.com/bag1",
    referenceUrl2: "https://buyma.com/bag1",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "モノグラム・スピーディ25",
    representativeCheck: true,
    judgmentResult: false,
    feedback: "相場を高く見積もりすぎた",
    feedbackConfirmed: true,
    winningSuccess: false,
    auctionDate: "2026-02-10",
    createdAt: "2026-02-10T09:00:00Z",
    updatedAt: "2026-02-11T10:00:00Z",
  },
  {
    id: "b2",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/bag2",
    brandName: "シャネル",
    check: true,
    bidTarget: true,
    assignee: "伊藤さん",
    revisedMarketPrice: null,
    marketPrice: 320000,
    bidPrice: 295000,
    wholesalePrice: 355000,
    referenceUrl1: "https://mercari.com/bag2",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "マトラッセ・クラシックフラップ",
    representativeCheck: true,
    judgmentResult: true,
    feedback: "相場判断が正確だった",
    feedbackConfirmed: false,
    winningSuccess: true,
    auctionDate: "2026-02-12",
    createdAt: "2026-02-12T10:00:00Z",
    updatedAt: "2026-02-13T09:00:00Z",
  },
  {
    id: "b3",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/bag3",
    brandName: "エルメス",
    check: true,
    bidTarget: true,
    assignee: "望月さん",
    revisedMarketPrice: null,
    marketPrice: 850000,
    bidPrice: 790000,
    wholesalePrice: null,
    referenceUrl1: "https://mercari.com/bag3",
    referenceUrl2: "https://rakuten.co.jp/bag3",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "バーキン30・トゴ・ブラック",
    representativeCheck: true,
    judgmentResult: true,
    feedback: "高額商品だが相場把握が的確",
    feedbackConfirmed: false,
    winningSuccess: true,
    auctionDate: "2026-02-14",
    createdAt: "2026-02-14T09:00:00Z",
    updatedAt: "2026-02-15T11:00:00Z",
  },
  {
    id: "b4",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/bag4",
    brandName: "グッチ",
    check: true,
    bidTarget: false,
    assignee: "折出さん",
    revisedMarketPrice: 62000,
    marketPrice: 58000,
    bidPrice: 52000,
    wholesalePrice: 65000,
    referenceUrl1: "https://mercari.com/bag4",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "ディオニュソス・GGスプリーム",
    representativeCheck: true,
    judgmentResult: false,
    feedback: "相場見積もりが低すぎた",
    feedbackConfirmed: true,
    winningSuccess: false,
    auctionDate: "2026-02-18",
    createdAt: "2026-02-18T10:00:00Z",
    updatedAt: "2026-02-19T14:00:00Z",
  },
  {
    id: "b5",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/bag5",
    brandName: "ボッテガ・ヴェネタ",
    check: true,
    bidTarget: true,
    assignee: "吉川さん",
    revisedMarketPrice: null,
    marketPrice: 180000,
    bidPrice: 165000,
    wholesalePrice: 200000,
    referenceUrl1: "https://mercari.com/bag5",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "カセット・マキシイントレチャート",
    representativeCheck: false,
    judgmentResult: true,
    feedback: "",
    feedbackConfirmed: false,
    winningSuccess: true,
    auctionDate: "2026-02-20",
    createdAt: "2026-02-20T09:00:00Z",
    updatedAt: "2026-02-20T09:00:00Z",
  },
  {
    id: "b6",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/bag6",
    brandName: "プラダ",
    check: false,
    bidTarget: false,
    assignee: "",
    revisedMarketPrice: null,
    marketPrice: null,
    bidPrice: null,
    wholesalePrice: null,
    referenceUrl1: "",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "",
    representativeCheck: false,
    judgmentResult: false,
    feedback: "",
    feedbackConfirmed: false,
    winningSuccess: false,
    auctionDate: "2026-02-22",
    createdAt: "2026-02-22T09:00:00Z",
    updatedAt: "2026-02-22T09:00:00Z",
  },
  {
    id: "b7",
    productUrl: "https://page.auctions.yahoo.co.jp/jp/auction/bag7",
    brandName: "フェンディ",
    check: false,
    bidTarget: false,
    assignee: "伊藤さん",
    revisedMarketPrice: null,
    marketPrice: null,
    bidPrice: null,
    wholesalePrice: null,
    referenceUrl1: "",
    referenceUrl2: "",
    referenceUrl3: "",
    referenceUrl4: "",
    referenceUrl5: "",
    notes: "",
    representativeCheck: false,
    judgmentResult: false,
    feedback: "",
    feedbackConfirmed: false,
    winningSuccess: false,
    auctionDate: "2026-02-23",
    createdAt: "2026-02-23T09:00:00Z",
    updatedAt: "2026-02-23T09:00:00Z",
  },
];

// ── エクスポート ───────────────────────────────────────────

/** カテゴリーキーに対応するサンプルデータを返す */
export function getSampleItems(categoryKey: string): AuctionItem[] {
  switch (categoryKey) {
    case "bags":    return sampleItemsBags;
    case "apparel": return sampleItemsApparel;
    default:        return sampleItemsApparel;
  }
}

/** 後方互換性のため残す（デフォルトはアパレル） */
export const sampleItems = sampleItemsApparel;
